test: &default

  # Credentials for REST APIs
  client_id: AR_uibq_qyvr5PS84BytAvJukHdw9i-f71JAPHmWag1tV1798rsB4X069wo5vYWfH1yR4AX8uGTPeL5D
  client_secret: EByaAh2NjBvQFUPdCh5gzRV2-HjCI-HqOixbbhu8IQJ8_Nec62WjagXIxNFaXPkcPf1O8DrnbLqJKd_6

  # Mode can be 'live' or 'sandbox'
  mode: sandbox
  ssl_options:
    ca_file: null

development:
  <<: *default

production:
  <<: *default
  mode: live
