test: &default

  # Credentials for REST APIs
  client_id: AXC_9lA7efsjxEgaSqs3Zy1k7Pw5El5hHF7pAKHHrgV26P2-BtZX0WvTWS1bYJ-Db863ZW1G1rRWExDv
  client_secret: EJkXoX7dGUwlvJnP_jtnLgnAEE1DfNn4Hancn3mtxkbar3yClE5ealE8cKBQ42yaQOmNwZpNym8KhXFT

  # Mode can be 'live' or 'sandbox'
  mode: sandbox
  ssl_options:
    ca_file: null

development:
  <<: *default

production:
  <<: *default
  mode: live
